@startuml
class TagNameCreator <<static>> {
    - <<const>> ITEM_NAME : string = "Tools/Create Constant/Tag Name"
    - <<const>> PATH : string = "Assets/MyAssets/Scripts/Constants/TagName.cs"
    - {static} <<readonly>> FILENAME : string
    - {static} <<readonly>> FILENAME_WITHOUT_EXTENSION : string
    + {static} Create() : void
    + {static} CreateScript() : void
    + {static} CanCreate() : bool
    + {static} RemoveInvalidChars(str:string) : string
}
@enduml
